### ISSUE TITLE
[ETHSG 2018] - Historical Data Tool

### ISSUE THREAD

**Issue by Anyhowclick** [KyberNetwork/hackathon-bounties#11]
## Historical Data Tool
Create an interface or API where users can query historical price and volume trade data of the different tokens supported on Kyber. This data should be cached to quicken access by 3rd party applications who require such data.

For price data, the easier option is to include an old block number into a web3 query, collate the information and present it using Tradeview or similar tools.

### Getting Started
Our [developer portal](https://developer.kyber.network/) is the place to go!

### Submission Criteria
1. Leave a comment below with a link to a Github repository.
2. The repository must be open-source.
3. The project must not have been worked on prior to the hackathon (ie. it should not be a pre-existing project).
4. A README document describing the project.
5. URLs to any publicly accessible web-interfaces and demo credentials if applicable.
6. Photo of your team at ETHSG (even better yet, taking one with us at our booth!)
7. Submission deadline will be 9 December 2018, 0930 hrs (GMT+8).

### Prize
SGD $2000 worth of KNC tokens!

#### 1. User Experience (30%)
Intuitive, easy to use and interact with. 

#### 2. Technical Difficulty (35%)
Going above and beyond of what we specified. Good code quality, bug free, with thorough documentation.

#### 3. Usability (30%)
Other projects are able to build on top of your application, or incorporate it into their own.

#### 4. X Factor (5%)
Something that makes us go "Wow!"

### Contacting Us
We will have a booth set up during the event, so just drop by to meet us! A number of us will be around during the event to assist with any questions you may have! Additionally, you may join our [developer group on Telegram!](https://t.me/kyberdeveloper)

**Comment by siddhanjay** [comment]
Hi Kyber team,
Here is our project submission for this bounty

https://github.com/siddhanjay/KyberWatch
