### ISSUE TITLE
[ETHSG 2018] - Set Protocol Issuance Relayer

### ISSUE THREAD

**Issue by Anyhowclick** [KyberNetwork/hackathon-bounties#12]
## Set Protocol Issuance Relayer
Build an issuance relayer that taps on liquidity provided from Kyber’s reserves and from other liquidity providers like 0x. This enables users to obtain competitive prices for their Set, while also providing savvy market takers with arbitrage opportunities.

### Getting Started
Check out our [developer portal](https://developer.kyber.network/) and [Set Protocol's documentation](https://docs.setprotocol.com)!

### Submission Criteria
1. Leave a comment below with a link to a Github repository.
2. The repository must be open-source.
3. The project must not have been worked on prior to the hackathon (ie. it should not be a pre-existing project).
4. A README document describing the project.
5. URLs to any publicly accessible web-interfaces and demo credentials if applicable.
6. Photo of your team at ETHSG (even better yet, taking one with us at our booth!)
7. Submission deadline will be 9 December 2018, 0930 hrs (GMT+8).

### Prize
SGD $1000. **This is a joint bounty hosted together with Set Protocol.**

#### 1. User Experience (30%)
Intuitive, easy to use and interact with. 

#### 2. Technical Difficulty (35%)
Going above and beyond of what we specified. Good code quality, bug free, with thorough documentation.

#### 3. Usability (30%)
Other projects are able to build on top of your application, or incorporate it into their own.

#### 4. X Factor (5%)
Something that makes us go "Wow!"

### Contacting Us
We will have a booth set up during the event, so just drop by to meet us! A number of us will be around during the event to assist with any questions you may have! Additionally, you may join our [developer group on Telegram!](https://t.me/kyberdeveloper)

**Comment by deacix** [comment]
Project DepoSet

Github Link: https://github.com/CryptoManiacsZone/DepoSet
