### ISSUE TITLE
[EDCON 2019] Integrate Kyber's protocol into a DApp that utilises one of the scaling solutions

### ISSUE THREAD

**Issue by ghost** [KyberNetwork/hackathon-bounties#15]
**Bounty theme**
Build a DApp that utilises one of the scaling solutions and integrate Kyber's protocol on top to handle the payment / swapping service!

***Suggestions***
- Make a game using state channels. Reward the winner in the token of their choice. 
- Enhance existing payment channels to allow payments off-chain in any token.
- Allow users to deposit and withdraw in any token from an application built on a side chain.

**Getting Started**
Check out our [developer portal](https://developer.kyber.network/docs/Start/)!

**Submission Criteria**
Leave a comment below with a link to a Github repository.
The repository must be open-source.
The project must not have been worked on prior to the hackathon (ie. it should not be a pre-existing project).
A README document describing the project.
URLs to any publicly accessible web-interfaces and demo credentials if applicable.
Photo of your team at EDCON (even better yet, taking one with us at our booth!)
Submission deadline will be [10 April 2018, 0830 hrs (GMT+11)](https://www.edcon.io/hackathon).
Prize
USD $1500.

**Judging Criteria**
1. User Experience (30%)
Intuitive, easy to use and interact with.

2. Technical Difficulty (35%)
Going above and beyond of what we specified. Good code quality, bug free, with thorough documentation.

3. Usability (30%)
Other projects are able to build on top of your application, or incorporate it into their own.

4. X Factor (5%)
Something that makes us go "Wow!"

**Contacting Us**
We will have a booth set up during the event, so just drop by to meet us! A number of us will be around during the event to assist with any questions you may have! Additionally, you may join our developer group on Telegram!

**Comment by ayobuenavista** [comment]
EDCON event finished
